version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: DockerFile
      args:
        - DATABASE_URL=${DATABASE_URL}
        - JWT_SECRET=${JWT_SECRET}
        - UPLOADTHING_SECRET=${UPLOADTHING_SECRET}
        - UPLOADTHING_APP_ID=${UPLOADTHING_APP_ID}
        - UPLOADTHING_TOKEN=${UPLOADTHING_TOKEN}
        - RESEND_API_KEY=${RESEND_API_KEY}
        - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - UPLOADTHING_SECRET=${UPLOADTHING_SECRET}
      - UPLOADTHING_APP_ID=${UPLOADTHING_APP_ID}
      - UPLOADTHING_TOKEN=${UPLOADTHING_TOKEN}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
